import _ from 'lodash';

export class Currency {
  searchKeyword;
  selectedCurrency;
  displayedCurrencies;
  currencyAsArray;
  nameAsArray;
  currencyFullName = {
    AUD: 'Australlian Dollar',
    BRL: 'Brazilian Real',
    CAD: 'Canadian Dollar',
    CHF: 'Swiss Franc',
    EUR: 'Euro',
    GBP: 'British Pound',
    HKD: 'Hong Kong Dollar',
    IDR: 'Indonesian Rupiah',
    INR: 'Indian Rupee',
    JPY: 'Japanese Yen',
    KRW: 'Korean Won',
    MYR: 'Malaysian Ringgit',
    NZD: 'New Zealand Dollar',
    PHP: 'Philippine Peso',
    PLN: 'Polish Zloty',
    RUB: 'Russian Ruble',
    SGD: 'Singapore Dollar',
    THB: 'Thai Baht',
    TRY: 'Turkish Lira',
    TWD: 'New Taiwan Dollar',
    USD: 'United States Dollar'
  };
  currencySymbols = {
    AED: 'د.إ',
    AFN: 'Af',
    ALL: 'L',
    AMD: 'Դ',
    ANG: 'ƒ',
    AOA: 'Kz',
    ARS: '$',
    AUD: '$',
    AWG: 'ƒ',
    AZN: '₼',
    BAM: 'KM',
    BBD: '$',
    BDT: '৳',
    BGN: 'лв',
    BHD: 'ب.د',
    BIF: '₣',
    BMD: '$',
    BND: '$',
    BOB: '$b',
    BRL: 'R$',
    BSD: '$',
    BTC: 'BTC',
    BTN: 'Nu.',
    BWP: 'P',
    BYN: 'Br',
    BYR: 'Br',
    BZD: 'BZ$',
    CAD: '$',
    CDF: '₣',
    CHF: '₣',
    CLF: 'CLF',
    CLP: '$',
    CNY: '¥',
    COP: '$',
    CRC: '₡',
    CUC: 'CUC',
    CUP: '₱',
    CVE: '$',
    CZK: 'Kč',
    DJF: '₣',
    DKK: 'kr',
    DOP: 'RD$',
    DZD: 'د.ج',
    EGP: '£',
    ERN: 'Nfk',
    ETB: 'Br',
    EUR: '€',
    FJD: '$',
    FKP: '£',
    GBP: '£',
    GEL: 'ლ',
    GGP: '£',
    GHS: '¢',
    GIP: '£',
    GMD: 'D',
    GNF: '₣',
    GTQ: 'Q',
    GYD: '$',
    HKD: '$',
    HNL: 'L',
    HRK: 'kn',
    HTG: 'G',
    HUF: 'Ft',
    IDR: 'Rp',
    ILS: '₪',
    IMP: '£',
    INR: '₨',
    IQD: 'ع.د',
    IRR: '﷼',
    ISK: 'kr',
    JEP: '£',
    JMD: 'J$',
    JOD: 'د.ا',
    JPY: '¥',
    KES: 'Sh',
    KGS: 'лв',
    KHR: '៛',
    KMF: 'KMF',
    KPW: '₩',
    KRW: '₩',
    KWD: 'د.ك',
    KYD: '$',
    KZT: 'лв',
    LAK: '₭',
    LBP: '£',
    LKR: '₨',
    LRD: '$',
    LSL: 'L',
    LTL: 'LTL',
    LVL: 'LVL',
    LYD: 'ل.د',
    MAD: 'د.م.',
    MDL: 'L',
    MGA: 'MGA',
    MKD: 'ден',
    MMK: 'K',
    MNT: '₮',
    MOP: 'P',
    MRO: 'UM',
    MUR: '₨',
    MVR: 'ރ.',
    MWK: 'MK',
    MXN: '$',
    MYR: 'RM',
    MZN: 'MT',
    NAD: '$',
    NGN: '₦',
    NIO: 'C$',
    NOK: 'kr',
    NPR: '₨',
    NZD: '$',
    OMR: '﷼',
    PAB: 'B/.',
    PEN: 'S/.',
    PGK: 'K',
    PHP: '₱',
    PKR: '₨',
    PLN: 'zł',
    PYG: 'Gs',
    QAR: '﷼',
    RON: 'lei',
    RSD: 'Дин.',
    RUB: '₽',
    RWF: '₣',
    SAR: '﷼',
    SBD: '$',
    SCR: '₨',
    SDG: '£',
    SEK: 'kr',
    SGD: '$',
    SHP: '£',
    SLL: 'Le',
    SOS: '$',
    SRD: '$',
    STD: 'Db',
    SVC: '$',
    SYP: '£',
    SZL: 'L',
    THB: '฿',
    TJS: 'ЅМ',
    TMT: 'm',
    TND: 'د.ت',
    TOP: 'T$',
    TRY: '₤',
    TTD: 'TT$',
    TWD: 'NT$',
    TZS: 'Sh',
    UAH: '₴',
    UGX: 'Sh',
    USD: '$',
    UYU: '$U',
    UZS: 'лв',
    VEF: 'Bs',
    VND: '₫',
    VUV: 'Vt',
    WST: 'T',
    XAF: '₣',
    XAG: 'XAG',
    XAU: 'XAU',
    XCD: '$',
    XDR: 'XDR',
    XOF: 'franc',
    XPF: '₣',
    YER: '﷼',
    ZAR: 'R',
    ZMK: 'ZMK',
    ZMW: 'ZK',
    ZWL: '$'
  };

  constructor() {
    this.currencyAsArray = _.keys(this.currencyFullName);
    this.nameAsArray = _.values(this.currencyFullName);
    this.displayedCurrencies = _.clone(this.currencyAsArray);
  }
}